### ISSUE TITLE
Help with incorrect results

### ISSUE THREAD

**Issue by sagniklp** [BjoernHaefner/DepthSRfromShading#2]
I got the following output, which is not as expected:
![test](https://user-images.githubusercontent.com/10586359/77277425-41e8f580-6c93-11ea-9ddf-7387d5633f6a.png)

Could you help me debug the reason? I think I'm missing something.
Few notes:
* I'm getting a warning:
Update lightingWarning: Rank deficient, rank = 0, tol =  0.000000e+00. 
In depthSRfromShading>lightUpdate (line 394)
In depthSRfromShading (line 251)
In main (line 113)

* I've tried changing few parameters but didn't see much change. Could you please share the parameters you've used for this particular example?

Thank you!

**Comment by BjoernHaefner** [comment]
Hi @sagniklp,

it looks like there is some issue with the lighting and the albedo estimation.

First, let's try to make sure the code is doing the correct thing. Could you download [this file](https://vision.in.tum.de/_media/data/datasets/photometricdepthsr/realsense_android_sf2_sfs.zip) and run the code on it to see if the results are comparable as the ones visualized [here](https://vision.in.tum.de/data/datasets/photometricdepthsr#android).

The reason behind trying it on the linked dataset is, that we know that [DepthSRfromShading](https://github.com/BjoernHaefner/DepthSRfromShading) is working on it and to make sure the issue is not [Vase dataset](https://vision.in.tum.de/data/datasets/photometricdepthsr#vase) itself. The Vase dataset, the one that you're using, has been tested on the [SRmeetsPS code](https://github.com/pengsongyou/SRmeetsPS) only for now.

Best
Bjoern

**Comment by sagniklp** [comment]
![test_android](https://user-images.githubusercontent.com/10586359/77375528-27bb2000-6d44-11ea-9583-d61dba368dc2.png)

**Comment by BjoernHaefner** [comment]
Hi @sagniklp,

ok, it looks like there is something not correctly working. Did you make sure all the [requirements](https://github.com/BjoernHaefner/DepthSRfromShading#1-requirements) are fulfilled, i.e. did you
1) download and compile [minFunc](http://www.cs.ubc.ca/~schmidtm/Software/minFunc.html),
2) clone, build and **test** [MumfordShahCuda](https://github.com/BjoernHaefner/MumfordShahCuda),
3) download [inpaint_nans](https://de.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/4551/versions/2/download/zip), and
4) download and compile [CMG](http://www.cs.cmu.edu/~jkoutis/cmg.html)?

The MumfordShahCuda code must work correctly in order to get results and it looks like the estimated albedo (using MumfordShah code in the backend) is not doing the right thing.

Was there some output on command line when running the Android dataset?
What system are you running it on?
How did you compile and test MumfordShahCuda?

Best
Bjoern

**Comment by sagniklp** [comment]
Yeah, I've installed all of them. MumfordShahCuda is not working atm:
![testms](https://user-images.githubusercontent.com/10586359/77449968-051f1a80-6dc9-11ea-92f1-056217f87cb8.png)

Getting the same warning while running android dataset: Update lightingWarning: Rank deficient, rank = 0, tol = 0.000000e+00.
I'm in Ubuntu 16.04, CUDA 9.0, OpenCV 4.2, Matlab 2018b
Following is the make output:
-- MEXF=TRUE
-- EXEF=FALSE
-- CUDA=TRUE
-- DEBUG=FALSE
-- MATLAB_ROOT: /usr/local/MATLAB/R2018b
-- Matlab libraries were found.
-- LINKING CUDA LIBRARIES: 
-- CUDA_INCLUDE_DIRS: /usr/local/cuda-9.0/include
-- Configuring done
-- Generating done
-- Build files have been written to: /media/hilab/HiLabData/Sagnik/Folded-Document-Capture/CVC/DepthSRfromShading/third_party/mumfordshah/build
[ 14%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/src/lib/cuda/cuda_compile_1_generated_mumford_shah_kernels.cu.o
[ 28%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/src/lib/cuda/cuda_compile_1_generated_cuda_common.cu.o
[ 42%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/src/lib/cuda/cuda_compile_1_generated_cuda_kernels.cu.o
Scanning dependencies of target mumfordShahMEX
[ 57%] Building CXX object CMakeFiles/mumfordShahMEX.dir/src/mex/main_mex.cc.o
[ 71%] Building CXX object CMakeFiles/mumfordShahMEX.dir/src/lib/mumford_shah.cc.o
[ 85%] Building CXX object CMakeFiles/mumfordShahMEX.dir/src/lib/io_data.cc.o
[100%] Linking CXX shared library lib/mumfordShahMEX.mexa64
[100%] Built target mumfordShahMEX

**Comment by sagniklp** [comment]
Problem is the CUDA version. Following is the output when mumfordshah is compiled without CUDA:
![testnocuda](https://user-images.githubusercontent.com/10586359/77456749-128cd280-6dd2-11ea-882e-d8491935d952.png)

Thanks for your time!
