### ISSUE TITLE
question about parameter normalization

### ISSUE THREAD

**Issue by zhaomeng1028** [BjoernHaefner/DepthSRfromShading#4]
%% parameter normalization

mu = params.mu/( sum(mask_lr(:)) *    (mean(z0(mask_lr))/8.8314)^2 ) * size(I,3) * sum(mask(:));
nu = params.nu/( sum(mask(:))  *   abs(mean(z0(mask_lr))/8.8045)^2 ) * size(I,3) * sum(mask(:));

what are numbers 8.8314 and 0.8045 mean?

**Comment by BjoernHaefner** [comment]
Hi @zhaomeng1028,

Thank you for your interest in our code :)

In our evaluation in the paper, we performed the parameters evaluation based on a single data set. In order to get more robust parameter settings, we decided to do parameter normalization (post paper publication) when publishing the code. 

The hardcoded numbers are from the single data set in the paper, so it's basically a de-normalization step.

That being set. If you compute the parameters normalization (without the hardcoded numbers, ie set them to one) for the single data set we used in the paper, the result would be exactly the hardcoded numbers.

**Comment by zhaomeng1028** [comment]
sorry，I don't understand. If I use my own data,I should fix this as
mu = params.mu
nu = params.nu

Is that right?

**Comment by BjoernHaefner** [comment]
No, if you use your own data, you shouldn't have to touch anything beyond `main.m`.

**Comment by zhaomeng1028** [comment]
ok,thanks.
